# Generated by Django 4.2.1 on 2023-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfile',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
